:art: rename intent
Trampss/todomvc pull request #12
Opened 2017-11-07 10:48 UTC by guillaumecrespel

2017-11-07 11:12 UTC, fabienjuif commented on src/components/footer/footer.container.js
> +    onClearCompleted: () => dispatch(action('CLICK_CLEAR_COMPLETED')),
We should stick with `on`
ON_CLICK_CLEAR_COMPLETED

2017-11-07 11:12 UTC, fabienjuif requested changes
Stick with `ON`

2017-11-07 13:47 UTC, fabienjuif commented on src/components/todos/todos.container.js
> +    onCompleteAll: e => dispatch(action('COMPLETE_ALL_CHANGED', e.target.checked)),
clicked ? swaped ?

2017-11-07 13:47 UTC, fabienjuif commented on src/sagas/intents.js
> +  yield takeLatest('TODO_KEYDOWNED', (action) => {
keydowned ? is it English ?

2017-11-07 13:48 UTC, guillaumecrespel commented on src/sagas/intents.js
> +  yield takeLatest('TODO_KEYDOWNED', (action) => {
yes yes !

2017-11-08 21:39 UTC, fabienjuif approved these changes

2017-11-09 09:39 UTC, merged